import './App.css'
import Logo from './components/Logo'
import ai_img from '/imgs/modern-residential-district-with-green-roof-balcony-generated-by-ai.jpg'

function App() {
  return (
    <>
      <header>
        <Logo/>
        <nav>
          <a href='#about'>О нас</a>
          <a href='#portfolio'>Портфолио</a>
          <a href='#services'>Услуги</a>
          <a href='#questions'>Вопросы</a>
        </nav>
        <div className='contacts'>
          <a href='#' className="phone"></a>
          <a href='#' className="telegram"></a>
          <a href='#' className="whatsapp"></a>
        </div>
      </header>

      <main>
        <section className="intro">
          <div>
            <div className="left">
              <h1>
                Строительное проектирование<br/>
                <span className='bold italic'>BuildHunt</span>
              </h1>
              <div className='intro_words'>
                Проектируем индивидуальные частные дома<br/>
                в различных стилях по разным технологиям
              </div>
              <button className='upper'>
                Обсудить проект
              </button>
            </div>
            <div className="right">
              <img src={ai_img} alt="modern residential district with green roof balcony generated by ai"/>
            </div>
          </div>
        </section>
        
        <section className="portfolio"></section>
        <section className="services"></section>
        <section className="questions"></section>
      </main>

      <footer>
        <div className='footer_img'></div>
        <div className="footer">
          <div className="footer_info">
            <p>Строительное проектирование BuildHunt</p>
            <p>&copy; 2024 г. Тюмень</p>
          </div>
          <Logo/>
        </div>
      </footer>


      {/* <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p> */}
    </>
  )
}

export default App
